// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCb9N0Z-c4Zu-eETQatxRQ-S6bICJQOalU',
    appId: '1:644739712023:web:ef1869aa1800f9ee528852',
    messagingSenderId: '644739712023',
    projectId: 'moa-diary-app',
    authDomain: 'moa-diary-app.firebaseapp.com',
    storageBucket: 'moa-diary-app.appspot.com',
    measurementId: 'G-WNSQKZS5B7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArYxtAP-m5eVlFgtYnZlLwOOpYHS2uMX0',
    appId: '1:644739712023:android:f52d480944a09509528852',
    messagingSenderId: '644739712023',
    projectId: 'moa-diary-app',
    storageBucket: 'moa-diary-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmVvBwAnHn4X20sexURSv87CF0cImi-L4',
    appId: '1:644739712023:ios:04099a68726ef644528852',
    messagingSenderId: '644739712023',
    projectId: 'moa-diary-app',
    storageBucket: 'moa-diary-app.appspot.com',
    iosBundleId: 'com.project.moaDiaryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmVvBwAnHn4X20sexURSv87CF0cImi-L4',
    appId: '1:644739712023:ios:237d0b2600370fa2528852',
    messagingSenderId: '644739712023',
    projectId: 'moa-diary-app',
    storageBucket: 'moa-diary-app.appspot.com',
    iosBundleId: 'com.project.moaDiaryApp.RunnerTests',
  );
}
